/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.Options.OptionsPage;

import Admin.Options.Options;
import Login.Login;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Questions extends javax.swing.JFrame {

    /**
     * Creates new form Questions
     */
    public Questions() {
        initComponents();
        try {
            QuestionAccessLayer.setTable(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CrQ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        opB = new javax.swing.JTextField();
        CorrectOP = new javax.swing.JTextField();
        opC = new javax.swing.JTextField();
        opD = new javax.swing.JTextField();
        opA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        CrQ1 = new javax.swing.JButton();
        CrQ2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Paper = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CrQ.setText("Create Question");
        CrQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrQActionPerformed(evt);
            }
        });
        jPanel2.add(CrQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Questions");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 781, 68));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("D)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 30, 30));

        question.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        question.setText("Enter Question Here");
        question.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                questionMouseClicked(evt);
            }
        });
        question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionActionPerformed(evt);
            }
        });
        question.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                questionKeyPressed(evt);
            }
        });
        jPanel2.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 680, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Which Option Is Correct?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("C)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 30, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("A)");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("B)");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 30, 30));
        jPanel2.add(opB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, -1));

        CorrectOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrectOPActionPerformed(evt);
            }
        });
        jPanel2.add(CorrectOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, -1));
        jPanel2.add(opC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, -1));
        jPanel2.add(opD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 40, -1));
        jPanel2.add(opA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 40, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Options");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 140, 30));

        CrQ1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CrQ1.setText("Delete");
        CrQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrQ1ActionPerformed(evt);
            }
        });
        jPanel2.add(CrQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, 30));

        CrQ2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CrQ2.setText("Update");
        CrQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrQ2ActionPerformed(evt);
            }
        });
        jPanel2.add(CrQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno", "Paper", "Question", "Op A", "Op B ", "Op C  ", "Op D   ", "CorrectOP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Sno");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Paper");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Question");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Op A");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Op B ");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Op C  ");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Op D   ");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("CorrectOP");
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 130, 610, 390));

        Paper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ppl_1", "cpl_2" }));
        jPanel2.add(Paper, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 80, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bkg.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jTextField6.setText("jTextField2");
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrQActionPerformed
                QuestionBean bean =new QuestionBean(question.getText().toString(), opA.getText().toString(), opB.getText().toString(), opC.getText().toString(), opD.getText().toString(), CorrectOP.getText().toString(), Paper.getSelectedItem().toString());
        try {
            int rec=QuestionAccessLayer.addRec(bean);
            if(rec>0){
                question.setText("");
                opA.setText("");
                opB.setText("");
                opC.setText("");
                opD.setText("");
                CorrectOP.setText("");
                QuestionAccessLayer.setTable(jTable1);
                
                
                
                }
            else
            {
                JOptionPane.showMessageDialog(this, "Question not Created");
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_CrQActionPerformed

    private void questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionActionPerformed

    private void CorrectOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrectOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorrectOPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CrQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrQ1ActionPerformed

    private void CrQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrQ2ActionPerformed

  QuestionBean bean =new QuestionBean(question.getText().toString(), opA.getText().toString(), opB.getText().toString(), opC.getText().toString(), opD.getText().toString(), CorrectOP.getText().toString(), Paper.getSelectedItem().toString());
        try {
            int rec=QuestionAccessLayer.updRec(bean);
            if(rec>0){
                question.setText("");
                opA.setText("");
                opB.setText("");
                opC.setText("");
                opD.setText("");
                CorrectOP.setText("");
                QuestionAccessLayer.setTable(jTable1);
                
                JOptionPane.showMessageDialog(this, "Question Updated");
                }
            else
            {
                JOptionPane.showMessageDialog(this, "Question not Created");
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        


    }//GEN-LAST:event_CrQ2ActionPerformed

    private void questionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_questionMouseClicked
question.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_questionMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
int row=jTable1.getSelectedRow();
question.setText(model.getValueAt(row, 2).toString());
opA.setText(model.getValueAt(row, 3).toString());
opB.setText(model.getValueAt(row, 4).toString());
opC.setText(model.getValueAt(row, 5).toString());
opD.setText(model.getValueAt(row, 6).toString());
CorrectOP.setText(model.getValueAt(row, 7).toString());



    }//GEN-LAST:event_jTable1MouseClicked

    private void questionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_questionKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_questionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                new Questions().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CorrectOP;
    private javax.swing.JButton CrQ;
    private javax.swing.JButton CrQ1;
    private javax.swing.JButton CrQ2;
    private javax.swing.JComboBox<String> Paper;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField opA;
    private javax.swing.JTextField opB;
    private javax.swing.JTextField opC;
    private javax.swing.JTextField opD;
    private javax.swing.JTextField question;
    // End of variables declaration//GEN-END:variables
}
